AWSTemplateFormatVersion: 2010-09-09
Description: Setup for testing lambda-wasmtime in the AWS cloud
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  User:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: LambdaTestingPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowLambdaFullAccess
                Effect: Allow
                Action: lambda:*
                Resource: "*"
              - Sid: AllowPassingLambdaExecutionRole
                Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt LambdaExecutionRole.Arn
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref User
Outputs:
  LambdaExecutionRoleArn:
    Description: ARN of the lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
  UserArn:
    Description: IAM user with full access to DynamoDB
    Value: !GetAtt User.Arn
  UserAccessKeyId:
    Description: Access key id of the IAM user
    Value: !Ref AccessKey
  UserSecretAccessKey:
    Description: Secret access key of the IAM user
    Value: !GetAtt AccessKey.SecretAccessKey