#!/bin/bash

set -Eeuo pipefail

post_init_error() {
  curl -fsSLX POST "$API/init/error" -d '{"error":"runtime initialization failed"}'
}

trap post_init_error EXIT

API="http://$AWS_LAMBDA_RUNTIME_API/2018-06-01/runtime"
FILE="$LAMBDA_TASK_ROOT/${_HANDLER%%.*}.wasm"
HANDLER="${_HANDLER##*.}"
WARNING="warning: using \`--render\` with a function that returns values is experimental and may break in the future"
PREP_ENV_VARS="$(paste -sd "," <<< "$(env)")"

printf "env vars\n%s\nwasmtime version %s" "$(env)" "$(/opt/bin/wasmtime --version)"

trap - EXIT
set +Eeu

while :; do
  response="$(curl -fsSLD - "$API/invocation/next")"
  event="${response#*\\n\\n}"
  headers="${response%%\\n\\n*}"
  function_arn="$(grep -ioP "(?<=Lambda-Runtime-Invoked-Function-Arn: )([^[:space:]]*)" <<< "$headers")"
  deadline_ms="$(grep -ioP "(?<=Lambda-Runtime-Deadline-Ms: )([^[:space:]]*)" <<< "$headers")"
  trace_id="$(grep -ioP "(?<=Lambda-Runtime-Trace-Id: )([^[:space:]]*)" <<< "$headers")"
  request_id="$(grep -ioP "(?<=Lambda-Runtime-Aws-Request-Id: )([^[:space:]]*)" <<< "$headers")"
  context="{\"function_arn\":\"$function_arn\",\"deadline_ms\":\"$deadline_ms\",\"request_id\":\"$request_id\",\"trace_id\":\"$trace_id\"}"

  # maybe get rid of that last pipe 
  # bgdin d bloc?
  # allow /tmp?
  if result="$(/opt/bin/wasmtime --disable-cache --enable-simd --env="$PREP_ENV_VARS,_x_amzn_trace_id=$trace_id" --invoke="$HANDLER" "$FILE" "$event" "$context" 2>&1 | grep -v "$WARNING")"; then
    curl -fsSLX POST "$API/invocation/$request_id/response" -d "$result"
  else
    curl -fsSLX POST "$API/invocation/$request_id/error" -d "$result"
  fi
done