// Type for handler errors.
enum error {
    client-error,
    server-error,
}

///  Types available to a Lambda function.
///  Client context sent by the AWS Mobile SDK.
record client-context {
    ///  Information about the mobile application invoking the function.
    client: client-application,
    ///  Custom properties attached to the mobile event context.
    custom: list<tuple<string,string>>,
    ///  Environment settings from the mobile client.
    environment: list<tuple<string,string>>
}

///  AWS Mobile SDK client fields.
record client-application {
    ///  The mobile app installation id
    installation-id: string,
    ///  The app title for the mobile app as registered with AWS' mobile services.
    app-title: string,
    ///  The version name of the application as registered with AWS' mobile services.
    app-version-name: string,
    ///  The app version code.
    app-version-code: string,
    ///  The package name for the mobile application invoking the function
    app-package-name: string
}

///  Cognito identity information sent with the event
record cognito-identity {
    ///  The unique identity id for the Cognito credentials invoking the function.
    identity-id: string,
    ///  The identity pool id the caller is "registered" with.
    identity-pool-id: string
}

///  The Lambda function execution context. The values in this struct
///  are populated using the [Lambda environment variables](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)
///  and the headers returned by the poll request to the Runtime APIs.
record context {
    ///  The AWS request ID generated by the Lambda service.
    request-id: string,
    ///  The execution deadline for the current invocation in milliseconds.
    deadline: u64,
    ///  The ARN of the Lambda function being invoked.
    invoked-function-arn: string,
    ///  The X-Ray trace ID for the current invocation.
    xray-trace-id: string,
    ///  The client context object sent by the AWS mobile SDK. This field is
    ///  empty unless the function is invoked using an AWS mobile SDK.
    ///client-context: option<client-context>,
    ///  The Cognito identity that invoked the function. This field is empty
    ///  unless the invocation request to the Lambda APIs was made using AWS
    ///  credentials issues by Amazon Cognito Identity Pools.
    ///identity: option<cognito-identity>,
    ///  Lambda function configuration from the local environment variables.
    ///  Includes information such as the function name, memory allocation,
    ///  version, and log streams.
    /// env-config: config
}


///  Configuration derived from environment variables.
record config {
    ///  The name of the function.
    function-name: string,
    ///  The amount of memory available to the function in MB.
    memory: s32,
    ///  The version of the function being executed.
    version: string,
    ///  The name of the Amazon CloudWatch Logs stream for the function.
    log-stream: string,
    ///  The name of the Amazon CloudWatch Logs group for the function.
    log-group: string
}

type event = string
type output = string

handler: function(event: event, context: option<context>) -> expected<output, error>
