# lambda-wasmtime build spec 4 cargo-make
# 4 macos and ubuntu
# 4 setup run: cargo make install-deps
# 4 build run: cargo make runtime

# 1time `cargo make install-deps` 4 setup

[env]
ZIP_FILE = "${ZIP_FILE:-runtime.zip}"

[tasks.install-target]
command = "rustup"
args = ["target", "add", "x86_64-unknown-linux-musl"]

[tasks.apt-get-update]
command = "apt-get"
args = ["update", "-y"]

[tasks.apt-get-install-deps]
command = "apt-get"
args = ["install", "gcc", "g++", "cmake", "-y"]

[tasks.install-musl.linux]
command = "apt-get"
args = ["install", "musl-tools", "-y"]
dependencies = ["apt-get-update", "apt-get-install-deps"]

[tasks.install-musl.mac]
command = "brew"
args = ["install", "FiloSottile/musl-cross/musl-cross"]

[tasks.install-deps]
dependencies = ["install-target", "install-musl"]

# everyday cargo-make tasks

[tasks.build]
command = "cargo"
args = ["build", "--release", "--target=x86_64-unknown-linux-musl"]
dependencies = ["format", "clean"]

[tasks.build.linux]
env = { PKG_CONFIG_ALLOW_CROSS=true, CC_x86_64_unknown_linux_musl="musl-gcc", CXX_x86_64_unknown_linux_musl="g++" }

[tasks.build.mac]
env = { PKG_CONFIG_ALLOW_CROSS=true, CC_x86_64_unknown_linux_musl="x86_64-linux-musl-gcc", CXX_x86_64_unknown_linux_musl="x86_64-linux-musl-g++" }

[tasks.rename-exec]
command = "cp"
args = ["./target/x86_64-unknown-linux-musl/release/lambda-wasmtime", "./target/x86_64-unknown-linux-musl/release/bootstrap"]

[tasks.bundle]
env = { ZIP_FILE="./lambda_wasmtime.zip" }
command = "zip"
args = ["-mj", "${ZIP_FILE}", "./target/x86_64-unknown-linux-musl/release/bootstrap"]
dependencies = ["rename-exec"]

[tasks.runtime]
dependencies = ["build", "bundle"]