# TODO
# - make available 4 ubuntu and osx by finding a way to aalso compile on ubuntu
# - update release workflow to also build embedded wasmtime

# 1time cargo make install-deps 4 setup

[tasks.install-target]
command = "rustup"
args = ["target", "add", "x86_64-unknown-linux-musl"]

[tasks.install-musl]
command = "brew"
args = ["install", "FiloSottile/musl-cross/musl-cross"]

[tasks.install-deps]
dependencies = ["install-target", "install-musl"]

# everyday cargo make tasks

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
env = { PKG_CONFIG_ALLOW_CROSS="1", CC_x86_64_unknown_linux_musl="x86_64-linux-musl-gcc", CXX_x86_64_unknown_linux_musl="x86_64-linux-musl-g++" }
command = "cargo"
args = ["build", "--release", "--target=x86_64-unknown-linux-musl"]
dependencies = ["format", "clean"]

[tasks.rename-exec]
command = "cp"
args = ["./target/x86_64-unknown-linux-musl/release/lambda-wasmtime", "./target/x86_64-unknown-linux-musl/release/bootstrap"]

[tasks.bundle]
command = "zip"
args = ["-mj", "./lambda_wasmtime.zip", "./target/x86_64-unknown-linux-musl/release/bootstrap"]
dependencies = ["rename-exec"]

[tasks.all]
dependencies = ["build", "bundle"]