[package]
name = "handler"
version = "0.1.0"
authors = ["Noah Anabiik Schwarz <noah.anabiik.schwarz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
bytes = "1"
http  = "0.2"
serde_json = "1"
wasi-experimental-http = "0.9"

[package.metadata]
wasm-opt = false
