[package]
name = "demo"
version = "0.1.0"
authors = ["Noah Anabiik Schwarz <noah.anabiik.schwarz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
base64 = "0.3.1"
image = "0.22.3"
serde_json = "1.0.41"