[env]
DEMO_ZIP_FILE_NAME = { value = "demo.zip", condition = { env_not_set = ["DEMO_ZIP_FILE_NAME"] } }

[tasks.build]
command = "cargo"
args = ["wasi", "build", "--release"]

[tasks.bundle]
command = "zip"
args = ["-j", "./${DEMO_ZIP_FILE_NAME}", "./target/wasm32-wasi/release/demo.wasm"]

[tasks.demo]
dependencies = ["format", "clean", "build", "bundle"]