name: ci

on:
  push:
    branches:
      - master
      - embedded-wasmtime
  release:
    types:
      - created

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: LambdaWasmtimeTestFunction
  RUNTIME_ZIP_FILE_NAME: runtime.zip
  DEMO_ZIP_FILE_NAME: demo.zip
  VERSION: 0.3.3
  VERSION_DOTLESS: ${VERSION//./}
  DOCKER_BUILD_IMAGE_TAG: docker.pkg.github.com/chiefbiiko/lambda-wasmtime/runtime-build-image:0.3.3-amazonlinux2

jobs:
  build_image:
    name: build and publish the docker build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: build the build image
        run: |
          docker build \
            --file=./Dockerfile \
            --tag=${{ env.DOCKER_BUILD_IMAGE_TAG }} \
            .
      - name: docker.pkg.github.com login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} \
          | \
          docker login docker.pkg.github.com \
            --username=$GITHUB_ACTOR \
            --password-stdin
      - name: publish the build image 2 docker.pkg.github.com
        run: docker push ${{ env.DOCKER_BUILD_IMAGE_TAG }}
  build_runtime:
    name: build the runtime
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: docker.pkg.github.com login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} \
          | \
          docker login docker.pkg.github.com \
            --username=$GITHUB_ACTOR \
            --password-stdin
      - name: pull the build image 4rom docker.pkg.github.com
        run: docker pull ${{ env.DOCKER_BUILD_IMAGE_TAG }}
      - name: build the runtime in the custom build container
        run: |
          docker run \
            --rm \
            --volume=$PWD:/home \
            --env=RUNTIME_ZIP_FILE_NAME=${{ env.RUNTIME_ZIP_FILE_NAME }} \
            ${{ env.DOCKER_BUILD_IMAGE_TAG }}
      - name: upload the runtime layer artifact
        uses: actions/upload-artifact@v1
        with:
          name: runtime
          path: ${{ env.RUNTIME_ZIP_FILE_NAME }}
  build_demo:
    name: build the demo
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: docker.pkg.github.com login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} \
          | \
          docker login docker.pkg.github.com \
            --username=$GITHUB_ACTOR \
            --password-stdin
      - name: pull the build image 4rom docker.pkg.github.com
        run: docker pull ${{ env.DOCKER_BUILD_IMAGE_TAG }}
      - name: build the demo in the custom build container
        run: |
          docker run \
            --rm \
            --volume=$PWD:/home \
            --env=RUNTIME_ZIP_FILE_NAME=${{ env.RUNTIME_ZIP_FILE_NAME }} \
            ${{ env.DOCKER_BUILD_IMAGE_TAG }} \
              cargo make \
                --cwd=demo \
                --env=DEMO_ZIP_FILE_NAME=${{ env.DEMO_ZIP_FILE_NAME }} \
                demo
      - name: upload the demo bundle artifact
        uses: actions/upload-artifact@v1
        with:
          name: demo
          path: demo/${{ env.DEMO_ZIP_FILE_NAME }}
  test:
    name: test the runtime on AWS Lambda
    needs:
      - build_runtime
      - build_demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: download the runtime layer artifact
        uses: actions/download-artifact@v1
        with:
          name: runtime
      - name: download the demo bundle artifact
        uses: actions/download-artifact@v1
        with:
          name: demo
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: publish a new runtime layer version
        id: publish_layer
        run: |
          runtime_arn=$(
            aws lambda publish-layer-version \
              --layer-name=lambda_wasmtime_${{ env.VERSION_DOTLESS }} \
              --description="lambda-wasmtime ${{ env.VERSION }}" \
              --compatible-runtimes=provided \
              --license-info=MIT \
              --zip-file=fileb://runtime/${{ env.RUNTIME_ZIP_FILE_NAME }} \
            | \
            jq '.LayerVersionArn'
          )
          echo ::set-output name=runtime_arn::$runtime_arn
      - name: delete any existing test function
        if: |
          aws lambda get-function \
            --function-name=${{ env.LAMBDA_FUNCTION_NAME }}
        run: |
          aws lambda delete-function \
            --function-name=${{ env.LAMBDA_FUNCTION_NAME }}
      - name: deploy the demo lambda
        run: |
          aws lambda create-function \
            --function-name=${{ env.LAMBDA_FUNCTION_NAME }} \
            --runtime=provided \
            --role=${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }} \
            --handler=demo.handler \
            --description="lambda-wasmtime test function" \
            --timeout=3 \
            --memory-size=128 \
            --layers=${{ steps.publish_layer.outputs.runtime_arn }} \
            --zip-file=fileb://demo/${{ env.DEMO_ZIP_FILE_NAME }} \
          | \
          jq '.FunctionArn'
      - name: invoke the demo lambda
        run: |
          base64_image=$(base64 ./demo/luigi.png)
          time \
            aws lambda invoke \
              --function-name=${{ env.LAMBDA_FUNCTION_NAME }} \
              --log-type=Tail \
              --payload="{\"data\":\"$base64_image\"}" \
              ./response.json
          jq '.Payload.data' ./response.json \
          | \
          base64 \
            --decode \
          > \
          ./thumbnail.png
      - name: delete the demo lambda
        run: |
          aws lambda delete-function \
            --function-name=${{ env.LAMBDA_FUNCTION_NAME }}
      - name: check image and thumbnail sizes
        run: |
          image_size="$(wc -c ./demo/luigi.png | grep -Eo '[0-9]+')"
          thumbnail_size="$(wc -c ./thumbnail.png | grep -Eo '[0-9]+')"
          if [[ ! $thumbnail_size -lt $image_size ]]; then exit 1; fi