name: demo

on: [push, pull_request, release]

jobs:
  check:
    name: showcase a demo
    runs-on: ubuntu-latest
    steps:
      - name: clone repo@${{ github.ref }}
        uses: actions/checkout@v1.0.0
        with:
          ref: ${{ github.ref }}
      - name: install rust, cargo, rustup n more
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: install cargo wasi
        run: cargo install cargo-wasi
      - name: install node n npm
        uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: install wasmtime
        run: curl https://wasmtime.dev/install.sh -sSf | bash
      - name: run a demo
        run: |
          source ~/.profile # make wasmtime available
          bash ./demo/demo.sh "$(pwd)/demo"
          if [[ "$(wc -c ./demo/thumbnail.png | grep -oP '[0-9]+')" -eq "0" ]]; then exit 1; fi