name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    name: publish a release
    runs-on: ubuntu-latest
    steps:
      - name: clone repo@${{ github.ref }}
        uses: actions/checkout@v1.0.0
        with:
          ref: ${{ github.ref }}
      - name: shellcheck bootstrap script
        run: shellcheck -e SC2153 ./bootstrap # ignore false error
      - name: bundle lambda runtime layer
        run: |
          chmod 755 ./bootstrap ./bin/wasmtime
          zip -r ./lambda_wasmtime.zip ./bootstrap ./bin
      - name: create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./lambda_wasmtime.zip
          asset_name: lambda_wasmtime.zip
          asset_content_type: application/zip